-- -----------------------------------------------------
-- Insercion de Datos
-- -----------------------------------------------------

USE LabRem_Digital;

-- -----------------------------------------------------
-- Laboratorios
-- -----------------------------------------------------

INSERT INTO Laboratorios (area, nombre, descripcion) 
VALUES 
(DEFAULT,'Transmisor/Receptor UART','La experiencia tiene como objetivo validar el diseño e implementación de un Transmisor/Receptor UART en un dispositivo FPGA.\nSe desea que el estudiante genere competencias en evaluar, diagnosticar y corregir el diseño lógico de una interfaz UART en FPGA para el normal funcionamiento.\nLa comunicación se evalúa entre dos terminales:\n1)-dispositivo FPGA que contiene la interfaz uart\n2)-una PC que contiene una interfaz gráfica que monitorea la comunicación.\nEl dispositivo FPGA se conecta a la PC mediante un adaptador usb/uart el cual permite emular una comunicación en la PC mediante su puerto usb.\nEn la prueba de transmisión el estudiante debe:\n1)-Definir el mensaje que desea transmitir desde el dispositivo FPGA como una cadena de caracteres ascii. \n2)-Enviar los datos desde la interfaz hacia la PC\n3)-Chequear en la aplicación que monitorea el puerto serie que se recibe adecuadamente la cadena de caracteres.\nEn la prueba de recepción el estudiante debe:\n1)-Define el dato que desea enviar desde el monitor del puerto serie en la pc hacia la interfaz implementada en el dispositivo FPGA.\n2)-Enviar el dato desde la PC.\n3)-El dispositivo FPGA recibe el dato y lo visualiza en 8 leds disponibles en el sistema de desarrollo que aloja el dispositivo FPGA.\nFinalmente el estudiante debe identificar el error en el diseño lógico en caso de no ser correcta la cadena recibida o enviada por el dispositivo FPGA, lo corrige, reprograma y vuelve a repetir el procedimiento. Como resultado se desea visualizar tensiones (o estados lógicos) de bits de transmisión y recepción en función del tiempo.'),
(DEFAULT,'Transmisor/Receptor I2C','La experiencia tiene como objetivo validar el diseño e implementación de una comunicación serie sincrónica maestro-esclavo I2C en un dispositivo FPGA.\nSe desea que el estudiante adquiera competencias en evaluar, diagnosticar y corregir el diseño de una interfaz I2C en FPGA para el normal funcionamiento.\nLa comunicación I2C se evalúa entre dos terminales:\n1) dispositivo FPGA que hace las veces de maestro.\n2) una memoria EEPROM que hace las veces de esclavo. El dispositivo FPGA se conecta a la memoria mediante una interfaz I2C.\nDesde el dispositivo FPGA se solicita leer o escribir la memoria EEPROM.\n1-La lectura de un byte en la memoria se implementa visualizando en 8 leds la palabra binaria.\n2-La escritura se realiza enviando a la memoria la dirección de escritura y el dato a escribir.\nSe espera medir las Tensiones (o estados lógicos) de bits de transmisión y recepción en función del tiempo. Para visualización de resultados en el caso de leer la memoria se implementa mediante un conjunto de 8 leds, en caso de escritura se implementa escribiendo un dato en la memoria y luego, mediante un proceso de lectura chequeando ese dato en 8 leds en la placa de prueba.');

-- -----------------------------------------------------
-- Ensayos
-- -----------------------------------------------------

-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);


-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 1, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 1, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 2, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 2, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 2, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 2, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 3, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 3, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);